[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qze4dsjnugtm7u0meuz58wwlar6q0qetvlpqlk4r2cntctc7fw79v6z92vr"]

[[validator_account]]
address = "tnam1q8qkpjqj9pym5nc40lctm5yad8drjeug9sxdmql9"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "142.132.194.124:19904"

[validator_account.consensus_key]
pk = "tpknam1qrds53arzz3uegxznqps76t4s94c08pq9ctqjdkf26mpt5nwsks2ud6wl0h"
authorization = "signam1qqr2wp9nwgdpwtxgc2gas3r59x4vtaq4l6mga0k05f2w6j8gxdymt25k7zsf325xrm0elkdwcn6ydwzl0wkkxujyeuzv4afpl0yt0mg0jtvlwr"

[validator_account.protocol_key]
pk = "tpknam1qqu8jpz6q7dj9rqrnq0r550uqu26dc5hc4y72qp4nw4gye32a9kjyvs0w2z"
authorization = "signam1qztut778eqgz3pruk8ae8mhw4r99vtp5dcjm67pzlae34l3kpxlfa4063rsacprvpq9f9wpwxct0zgud7szt0d8luerdhrkz5g77emcvryhyna"

[validator_account.tendermint_node_key]
pk = "tpknam1qp99q5t064a5xd95ksnvqxjcwsdeymw5s6vkefely08nl6wh3dk450xjn5c"
authorization = "signam1qq3u45ldsw7mdvgm4mvsdrspye2dr3lyu5dzpgfue2xjyekyhg3xgrymshpra3d4938n297z0use7evzymvscz95p4m2c9wrpud67rqffqk9zw"

[validator_account.eth_hot_key]
pk = "tpknam1qypev3kjlrfzw9js3czx30ysptrt4pzh58scea9hpy4wdcgvm43f6ys6p9x6q"
authorization = "signam1qyv0fsaw9dnj9wqqrwxg3vsm2rsk9mmv8f4xaw3dlwhaj8nauhdew78cpvtps0mezw4ctle0gnepsa0sluv9a04kcalsue0p4w9j9nnpqyv0qjfd"

[validator_account.eth_cold_key]
pk = "tpknam1qyp46ntgn38knpx8e0c49gcg9z7tgueuckx0uafxfrkupx9ypt773agn2y7lk"
authorization = "signam1q9plsued8prkmxuqmca759sy7zusjwawtme47u6aeprswmyh7mqrve09v54gwyn82gwx6rwcdrtk2t72rwh2vxun5kmg8fdgxnqnkvk4qq2syj7z"

[validator_account.metadata]
email = "cryptosjnet@gmail.com"
discord_handle = "cryptosj.net"

[validator_account.signatures]
tpknam1qze4dsjnugtm7u0meuz58wwlar6q0qetvlpqlk4r2cntctc7fw79v6z92vr = "signam1qrh97z8g9truc7hy4qytrk43avww2ef2pk9aclt0gza606vmdjsyg7f8t4zdsyscg35xh89dh42479s8et6mfg754guzut4c3e59hngfahz5wn"

[[bond]]
source = "tpknam1qr37yj7d9al5yerzn68kn7gtttfh25fqk45wwwvmt8snwgp5zwrzvjfujne"
validator = "tnam1q8qkpjqj9pym5nc40lctm5yad8drjeug9sxdmql9"
amount = "2630000"

[bond.signatures]
tpknam1qr37yj7d9al5yerzn68kn7gtttfh25fqk45wwwvmt8snwgp5zwrzvjfujne = "signam1qzzr0g8nn90692nr9x2rweuevtlgazjhudpuv8y0petp5pnagvuyd0j4n6scgejupxzqh9xqr0w0sstfc2hzquapjjfyfjkflx66acq8gyu2th"
