[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qr37yj7d9al5yerzn68kn7gtttfh25fqk45wwwvmt8snwgp5zwrzvjfujne"]

[[validator_account]]
address = "tnam1qx5al0d7te7lf52p92shnfklssrwqacyx5gs7v5c"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "142.132.194.124:19904"

[validator_account.consensus_key]
pk = "tpknam1qrnxng2mugn2upt8t8nj0mn4zy365hmpat5jz7w5tn4lkkj2eu84jzcn8kv"
authorization = "signam1qr7xrl4gea0hwpj7qeeezrg99zzlt0ke4gsqeam0xwgn5ncj5sk4ymxj5q8nyqw53ah2duldae066k04yc5mm805xs2pzes0uk08w3gzh50raj"

[validator_account.protocol_key]
pk = "tpknam1qzkx6m3herxdwc4daenz80mflct4m6zaewe4vgpnznndd92ekkmvud3tapy"
authorization = "signam1qq9xu9vsyfattu3p3kn5htrlg3uvehsed8r06dfakn49pw8s34vsfcwcsw7fxz4kwm8d5cxqg2l2j35hj5yjf70396su67p799770mqrugfqhp"

[validator_account.tendermint_node_key]
pk = "tpknam1qp0093yau6jjdsly60zff5ua6jvrkrpd5y3pjradkqmkuh6ylcd9vvghtlr"
authorization = "signam1qz5ktpk8nvcj8wvmmrmh90av5yenlg5kvw66a4kp8tc2nextxqwf8pndltszwtlmhuzgf2yfzv5slej5n6heud7ksenr2crz6da2xjgqra4sz4"

[validator_account.eth_hot_key]
pk = "tpknam1qyp3n6820uc5u6ft5arq8aru5xpqal0v7gfanc73fea8q927702sq5gpgpc8y"
authorization = "signam1qxm9q5s5g4l7usxv4g0fvqc9en5285zy2ry438p38zat3q9cq2gfz6rn0vu2yteegsj6yv3qz7za3m2gaxhrszvfpyxk0pmn3etuk6fgqqjnzkzd"

[validator_account.eth_cold_key]
pk = "tpknam1qyp98vgm5p50g73rdvlcucqpkw9273zdewfzynjy4y7z46000m5w4rcs84as0"
authorization = "signam1qx0p3kj3u0yzy5cxf8230eknyf6n4lcpv9qdrhtxt0wzxvg4y78gvjux3vztuan92czyjgtnk68xr4en6raphy0we20mzyts2jtucjtcqqd0a53g"

[validator_account.metadata]
email = "cryptosjnet@gmail.com"
discord_handle = "cryptosj.net"

[validator_account.signatures]
tpknam1qr37yj7d9al5yerzn68kn7gtttfh25fqk45wwwvmt8snwgp5zwrzvjfujne = "signam1qqrvd2uedsl94dg5jtdhz9q8j7hu4353tuzlf9fllkwafdq74czelflgzkp7h5mpgw7ajuszrwmqd5a98tulw6khl8k6zf46c0qqlvs0t2apnu"

[[bond]]
source = "tnam1qx5al0d7te7lf52p92shnfklssrwqacyx5gs7v5c"
validator = "tnam1qx5al0d7te7lf52p92shnfklssrwqacyx5gs7v5c"
amount = "2630000"

[bond.signatures]
tpknam1qr37yj7d9al5yerzn68kn7gtttfh25fqk45wwwvmt8snwgp5zwrzvjfujne = "signam1qza305wx2gaetx45nk4xhqqfeasf2xlaah3nyfwfc0e8wjsrjwfkzqzn8uha5pm3k5vjz0vq50udpcaah7zemqkmty8mdeg9gy25r0g0gd2f53"
